version: '3.3'
services:
  jenkins:
    container_name: jenkins
    privileged: true
    ports:
      - '8080:8080'
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=Pluralsight!2#
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
